apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;

        root /usr/share/nginx/html;

        index index.html;

        server_name site.by www.site.by;

        location / {
        try_files $uri $uri/ =404;
        }

        location /api/ {
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_pass          http://frontend.example.local:8081;
        }

    }

    server {
        listen 80;
        listen [::]:80;
        server_name site.by www.site.by;
        return 301 https://$host$request_uri;
    }
